### ISSUE TITLE
enhancements to license binding

### ISSUE THREAD

**Issue by hellt** [srl-labs/srl-controller#25]
Consider the following use cases for license provisioning:

1) If a user specifies a model that does not require a license then the tag of their image should not matter

2) If a user specifies a model that does require a license and the user has provided a single "catch all" license then the tag of their image should not matter

3) If a user specifies a model that does require a license and the user has not provided a license or has provided a license that matches a specific version other than the one they provided then the failure should clearly output during topology creation 

4) treat `ga` tag the same as `latest`

_Originally posted by @alexmasi in https://github.com/srl-labs/srl-controller/pull/24#discussion_r995984363_

**Comment by alexmasi** [comment]
Any update on this? Bullet point 2 would be really helpful as we now ingest an image with a license but we reference it as the :ga (generally available) tag

**Comment by hellt** [comment]
Hi @alexmasi 
I replied in IM. As a summary: I will get to it eventually, sorry for the delay. It was not prioritized since we incorporated license into the image

**Comment by hellt** [comment]
ah I think this was also sorted before #40, (point 2), but seems with #40 it is even more robust
