### ISSUE TITLE
enabling ssh on nokia

### ISSUE THREAD

**Issue by Azharkuntoji** [srl-labs/srl-controller#6]
Hi Roman,

I am not sure if this is the right platform to address my query. If not please guide me to correct platform.
I am having trouble using SSH to SRL. I am deploying SRL in KNE environment along with Ixia-c.
I am able to bring it up and things are working fine. I need to enable ssh and fetch BGP/ISIS route details from srl.
 
I followed the below document to enable SSH. The ssh server is up and running but is not accepting any connections.
 https://documentation.nokia.com/srlinux/SR_Linux_HTML_R21-11/Configuration_Basics_Guide/configb-systmmgmt.html

i also tried below commands, I am not sure what should be my source address.
--{ candidate shared default }--[  ]--
# info system ssh-server
    system {
        ssh-server {
            network-instance mgmt {
                admin-state enable
                source-address [
                    1.1.1.1
                    1.1.1.2
                ]
            }
            network-instance default {
                admin-state enable
                source-address [
                    2.1.1.1
                    2.1.1.2
                ]
            }
        }
    }

Can you please help me with this ?

Thanks,
Azhar

**Comment by Azharkuntoji** [comment]
The HTML doc mentions the same thing to mention the Source-address.
I am using GCP cluster.

**Comment by hellt** [comment]
@Azharkuntoji can you check if your SSH packets arrive with a correct checksum? If you're trying to connect to SRL from the same host, it is likely that the checksums of the packets is random, since TCP TX offload is typically enabled and checksums are randomly generated
SR Linux expects correct checksums, and will drop packets with incorrect ones
